### ISSUE TITLE
Error in privacy manifest

### ISSUE THREAD

**Issue by JackieQi** [hypertrack/sdk-ios#6]
I used latest sdk version 5.5.2. But when I generate privacy report. I got this error. Please advise. Thanks.

Missing an expected key: 'NSPrivacyCollectedDataTypes' 
XXX.app/Frameworks/HyperTrack.framework/PrivacyInfo.xcprivacy

**Comment by ferologics** [comment]
@JackieQi hey, we'll be issuing a release adding the missing collected data types to privacy manifest shortly. thanks for the report 🙏

**Comment by ferologics** [comment]
@JackieQi this is closed with e4ab8ff in release [`5.5.3`](https://github.com/hypertrack/sdk-ios/releases/tag/5.5.3)
